change to modules
jumpingrivers/tfpbrowser pull request #10
Opened 2022-10-18 22:44 UTC by jr-nicola

- splits the code for the plot tab, and the tables tab, into two separate modules
- put the cluster_id drop down into a separate module as well
- still has same 2 notes on R CMD check as before (next step is fixing this)

2022-10-20 10:06 UTC, russHyde requested changes
Hi, it's mostly good. The new modules really neaten it up.

I've requested a couple of changes.

- The UI/Server functions were inconsistently named,
- the `all_files` variable is independently defined in two different modules and could be a function call or argument to the modules, 
- could you add some roxygen for the new modules.

2022-10-20 19:06 UTC, jr-nicola commented on R/module_tables.R
> +    })
I've added `get_all_files()` as a function, and called it in both modules instead

2022-10-20 19:08 UTC, jr-nicola commented on R/app_server.R
>    })
Yes - I've removed it (originally tried a different approach)

2022-10-20 19:08 UTC, jr-nicola commented on R/module_clusterid.R
> +# Module 1, which will allow to select a cluster ID
I've renamed to cluster_idUI etc.

2022-10-20 19:09 UTC, jr-nicola commented on R/module_clusterid.R
> +clusterid_ui = function(id) {
I've added comments to all modules

2022-10-27 11:51 UTC, russHyde approved these changes
LGTM

2022-10-27 12:30 UTC, merged