Cluster stats help
jumpingrivers/tfpbrowser pull request #71
Opened 2024-03-15 14:27 UTC by russHyde

Adds a help icon for the "Cluster statistics" panel. On clicking, this explains that the user should select a node in a tree-view, or in a scatter plot, and that data about that cluster can be downloaded or viewed within the cluster statistics panel.

~There may be better ways to implement this. I originally wanted the clickable icon to be inside the 'cluster statistics' accordion panel's title, but my attempts failed - on clicking the icon, the accordion panel opened, because icon-clicks propagated to the underlying accordion. This happened even if I added a click handler that (should have) prevented click propagation.~

The icon is added as a bootstrap popover. It therefore requires bootstrap v5. Hence, the project has been bumped to use bootstrap 5.

The UI component for the "Cluster statistics" is now generated by a function that is called by the main UI function. No matching server function has been added because the changes here only affected the UI-side of the app.

----

The help icon is now inside the title part of the accordion panel, and has been constructed so that clicking the icon causes the help text to be shown, but doesn't cause the underlying accordion to expand.

2024-03-15 14:32 UTC, russHyde commented
Before (no icon alongside "> Cluster statistics (....)")

![image](https://github.com/jumpingrivers/tfpbrowser/assets/7734886/b5354d9a-f447-4a18-8fb8-78600cded471)

2024-03-15 14:33 UTC, russHyde commented
Outdated

After, help unopened:

![image](https://github.com/jumpingrivers/tfpbrowser/assets/7734886/f70813b6-b724-4093-b131-2c9c0d102e4c)

2024-03-15 14:33 UTC, russHyde commented
After, help opened:

![image](https://github.com/jumpingrivers/tfpbrowser/assets/7734886/774f0453-737d-412a-998c-9af9fef430ee)

2024-03-18 10:57 UTC, timbrock commented
Goes a bit odd when wrapping on narrow screens. Looks like it's assosciated with the view menu rather than "Cluster statistics".

![Screenshot from 2024-03-18 10-54-29](https://github.com/jumpingrivers/tfpbrowser/assets/7906373/da0b02ed-21c1-4509-9a0d-c3996063128a)

2024-03-18 10:58 UTC, timbrock requested changes
Needs tweaking on narrow screens

2024-03-19 11:05 UTC, russHyde commented
After: Help unopened

![image](https://github.com/jumpingrivers/tfpbrowser/assets/7734886/90d5977a-99a4-4e55-96a4-4a3a3455485a)

2024-03-19 11:05 UTC, russHyde commented
After: help opened

![image](https://github.com/jumpingrivers/tfpbrowser/assets/7734886/0c59ee87-bb8f-4beb-b32a-cd9e1b99eef5)

2024-03-19 11:06 UTC, russHyde commented
and here's a nice tiny screen version:

2024-03-19 17:49 UTC, timbrock reviewed
Could we just add a bit of margin between the cluster statistics section and the stuff below? Other than, only problem might have is whether the "?" icon is big enough for tapping?

2024-03-21 10:38 UTC, russHyde commented
@timbrock I've increased the icon size from 1em to 1.5em; margins have been added to the accordion and the accordion-item inside it, consistent with those that were applied to the summary/details that the accordion has replaced.

2024-03-21 10:39 UTC, russHyde commented
Now the app looks like this:
![image](https://github.com/jumpingrivers/tfpbrowser/assets/7734886/d7981c37-089e-4ec9-acf0-54e813cfbaa8)

2024-04-16 09:07 UTC, timbrock approved these changes
Looks like all my little issues have been fixed

2024-04-16 09:59 UTC, merged